---
fixes:
  - |
    Nexus:  Eliminate warning message for 'MultiConfigParser' from Nexus ML2 Plugin

    The 'MultiConfigParser' class is deprecated as seen by warnings in the neutron
    log file.  Refer to https://bugs.launchpad.net/networking-cisco/+bug/1712853
    for details.
