---
features:
    - |
      Nexus: Configure pool for port channel creation

      The user config 'vpc_pool' can add/remove entries from
      an existing cisco vpcid pool data base by changing its
      value and restarting neutron for the change to take affect.
      Existing VPC ids in the data base will be gathered and compared
      against the user's new vpc_pool config. New configured
      vpcids not found in the data base will be added. Inactive
      entries in the data base not found in the user's configured
      list will be removed. For more details, refer to file
      networking-cisco/etc/neutron/plugins/ml2/ml2_conf_cisco.ini
fixes:
    - |
      Nexus: Fix Syntax to Port Channel Pool

      There was a small window where vpc_pool syntax was incorrect.
      Changes were made to 'vpc_pool' to be consistent with other
      configs where range values are separated by '-' instead of a ','
      and you can have any number of ranges and single values separated
      by ',' which was not previously handled. So as an example,
      previously vpc_pool=10,20 configured vpcids 10 through 20
      and was limited to this config.  You could not have multiple
      ranges. Now you can configure vpc_pool=10-20,15-25,30 which
      gives you vpcids 10 through 20 and 15 through 25 and 30
      configured in the vpcid alloc db.
