# Copyright 2016 Cisco Systems, Inc.
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#


description "CPNR DNS Relay Conf"

start on runlevel [2345]
stop on runlevel [!2345]

env DST="/usr/local/bin/"

pre-start script
    logger -t cpnr-dns-relay.conf "Pre-Starting CPNR DNS Relay Agent"
    test -r $DST/cpnr-dns-relay-agent || { stop; exit 0; }
    logger -t cpnr-dns-relay.conf "Starting CPNR DNS Relay Agent"
end script

pre-stop script
    logger -t cpnr-dns-relay.conf "Stopping CPNR DNS Relay Agent"
end script

script
    logger -t cpnr-dns-relay.conf "Starting NOW CPNR DNS Relay Agent"
    exec $DST/cpnr-dns-relay-agent --config-file /etc/neutron/dhcp_agent.ini
    --log-file /var/log/cpnr/cpnr-dns-relay-agent.log
end script

